apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: obser
spec:
  ports:
    - port: 9200
      name: http
  selector:
    app: elasticsearch

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: obser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
          env:
            - name: discovery.type
              value: single-node
          ports:
            - containerPort: 9200
